  
spring:
  datasource:
    url: jdbc:postgresql://rev-can-training.czbbfxriy83g.ca-central-1.rds.amazonaws.com:5432/storedb
    username: storeuser
    password: Passw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      
  security:
   jwt:
    token:
      secret-key: JWTSuperSecretKey
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds

#spring.datasource.url= jdbc:postgresql://rev-canada-training.cgz20kzsu2zt.us-east-2.rds.amazonaws.com:5432/blankdb
#spring.datasource.username= blankuser
#spring.datasource.password= password
#spring.datasource.driver-class-name=org.postgresql.Driver 
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#
## Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
#spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
#
## seems like we don't need to put the below driver properties in application.properties file for latest version of postgreSQL.
#
##
#### Hibernate Properties
### The SQL dialect makes Hibernate generate better SQL for the chosen database
##spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5Inn
#spring.jpa.hibernate.show-sql=true
#spring.jpa.hibernate.ddl-auto = none
#app.jwtSecret= JWTSuperSecretKey
#app.jwtExpirationInMs = 604800000